### PR TITLE
new features

### PR DESCRIPTION
**Pull request by KeatonSushi**
aded some cool stuff. hope you enjoy

### CODE REVIEW

**Review by LitterPic — APPROVED** [review]

**Comment by KeatonSushi** [comment]
im not sure of how to fix the logo in the navbar. the only way that i know
for sure would fix it is to remove the cloudflare link.

**Comment by LitterPic** [comment]
I have another ticket to change the nav bar background to white, that will fix the logo issue since the user wont be able to tell that its overflowing the bar.

**Comment by KeatonSushi** [comment]
Oh okay.

**Comment by KeatonSushi** [comment]
i fixed the heart button color. can you resend the green logo for the
navbar.

**Pull request merged**
